name: Working
on  :
  workflow_dispatch:
    inputs:
      ovh_endpoint:
        description: "OVH Endpoint"
        type       : choice
        required   : true
        options    :
          - ovh-eu
          - ovh-ca
      ovh_application_key:
        description: "OVH Application Key"
        type       : string
        required   : true
        default    : random
      ovh_application_secret:
        description: "OVH Application Secret"
        type       : string
        required   : true
        default    : random
      ovh_consumer_key:
        description: "OVH Consumer Key"
        type       : string
        required   : true
        default    : random
env:
  GH_TOKEN: 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
jobs:
  ovh_endpoint:
    uses: aaurizon/action/.github/workflows/gh-set-secret.yaml@v1
    with:
      secret_name : ovh_endpoint
      secret_value: ${{ github.event.inputs.ovh_endpoint }}
    secrets:
      TOKEN: ${{ secrets.MY_TOKEN }}
  ovh_application_key:
    uses: aaurizon/action/.github/workflows/gh-set-secret.yaml@v1
    with:
      secret_name : ovh_application_key
      secret_value: ${{ github.event.inputs.ovh_application_key }}
    secrets:
      TOKEN: ${{ secrets.MY_TOKEN }}
  ovh_application_secret:
    uses: aaurizon/action/.github/workflows/gh-set-secret.yaml@v1
    with:
      secret_name : ovh_application_secret
      secret_value: ${{ github.event.inputs.ovh_application_secret }}
    secrets:
      TOKEN: ${{ secrets.MY_TOKEN }}
  ovh_consumer_key:
    uses: aaurizon/action/.github/workflows/gh-set-secret.yaml@v1
    with:
      secret_name : ovh_consumer_key
      secret_value: ${{ github.event.inputs.ovh_consumer_key }}
    secrets:
      TOKEN: ${{ secrets.MY_TOKEN }}
